#ifndef COMPREHEND_OPCODES_H
#define COMPREHEND_OPCODES_H

namespace Comprehend {

enum {
	OPCODE_UNKNOWN,
	OPCODE_TEST_FALSE,
	OPCODE_HAVE_OBJECT,
	OPCODE_OR,
	OPCODE_IN_ROOM,
	OPCODE_VAR_EQ,
	OPCODE_CURRENT_OBJECT_TAKEABLE,
	OPCODE_OBJECT_PRESENT,
	OPCODE_ELSE,
	OPCODE_OBJECT_IN_ROOM,
	OPCODE_OBJECT_NOT_VALID,
	OPCODE_INVENTORY_FULL,
	OPCODE_TEST_FLAG,
	OPCODE_CURRENT_OBJECT_IN_ROOM,
	OPCODE_HAVE_CURRENT_OBJECT,
	OPCODE_OBJECT_IS_NOT_NOWHERE,
	OPCODE_CURRENT_OBJECT_PRESENT,
	OPCODE_TEST_ROOM_FLAG,
	OPCODE_NOT_HAVE_OBJECT,
	OPCODE_NOT_IN_ROOM,
	OPCODE_CURRENT_OBJECT_IS_NOWHERE,
	OPCODE_OBJECT_NOT_PRESENT,
	OPCODE_OBJECT_NOT_IN_ROOM,
	OPCODE_TEST_NOT_FLAG,
	OPCODE_NOT_HAVE_CURRENT_OBJECT,
	OPCODE_OBJECT_IS_NOWHERE,
	OPCODE_CURRENT_OBJECT_NOT_PRESENT,
	OPCODE_CURRENT_OBJECT_NOT_TAKEABLE,
	OPCODE_TEST_NOT_ROOM_FLAG,
	OPCODE_INVENTORY,
	OPCODE_TAKE_OBJECT,
	OPCODE_MOVE_OBJECT_TO_ROOM,
	OPCODE_SAVE_ACTION,
	OPCODE_MOVE_TO_ROOM,
	OPCODE_VAR_ADD,
	OPCODE_SET_ROOM_DESCRIPTION,
	OPCODE_MOVE_OBJECT_TO_CURRENT_ROOM,
	OPCODE_VAR_SUB,
	OPCODE_SET_OBJECT_DESCRIPTION,
	OPCODE_SET_OBJECT_LONG_DESCRIPTION,
	OPCODE_MOVE,
	OPCODE_MOVE_DIRECTION,
	OPCODE_PRINT,
	OPCODE_REMOVE_OBJECT,
	OPCODE_SET_FLAG,
	OPCODE_CALL_FUNC,
	OPCODE_TURN_TICK,
	OPCODE_CLEAR_FLAG,
	OPCODE_INVENTORY_ROOM,
	OPCODE_TAKE_CURRENT_OBJECT,
	OPCODE_SPECIAL,
	OPCODE_DROP_OBJECT,
	OPCODE_DROP_CURRENT_OBJECT,
	OPCODE_SET_ROOM_GRAPHIC,
	OPCODE_SET_OBJECT_GRAPHIC,
	OPCODE_REMOVE_CURRENT_OBJECT,
	OPCODE_DO_VERB,
	OPCODE_VAR_INC,
	OPCODE_VAR_DEC,
	OPCODE_MOVE_CURRENT_OBJECT_TO_ROOM,
	OPCODE_DESCRIBE_CURRENT_OBJECT,
	OPCODE_SET_STRING_REPLACEMENT,
	OPCODE_SET_CURRENT_NOUN_STRING_REPLACEMENT,
	OPCODE_CURRENT_NOT_OBJECT,
	OPCODE_CURRENT_IS_OBJECT,
	OPCODE_DRAW_ROOM,
	OPCODE_DRAW_OBJECT,
	OPCODE_WAIT_KEY
};

class OpcodeMap {
public:
	OpcodeMap() {
		memset(_map, OPCODE_UNKNOWN, sizeof(_map));
	}
	~OpcodeMap();

	uint8 _map[0x100];
};

class OpcodeMapV1 : public OpcodeMap {
public:
	OpcodeMapV1() : OpcodeMap() {
		_map[0x01] = OPCODE_HAVE_OBJECT;
		_map[0x04] = OPCODE_OR;
		_map[0x05] = OPCODE_IN_ROOM;
		_map[0x06] = OPCODE_VAR_EQ;
		_map[0x08] = OPCODE_CURRENT_OBJECT_TAKEABLE;
		_map[0x09] = OPCODE_OBJECT_PRESENT;
		_map[0x0c] = OPCODE_ELSE;
		_map[0x0e] = OPCODE_OBJECT_IN_ROOM;
		_map[0x14] = OPCODE_OBJECT_NOT_VALID;
		_map[0x18] = OPCODE_INVENTORY_FULL;
		_map[0x19] = OPCODE_TEST_FLAG;
		_map[0x1d] = OPCODE_CURRENT_OBJECT_IN_ROOM;
		_map[0x20] = OPCODE_HAVE_CURRENT_OBJECT;
		_map[0x21] = OPCODE_OBJECT_IS_NOT_NOWHERE;
		_map[0x24] = OPCODE_CURRENT_OBJECT_PRESENT;
		_map[0x31] = OPCODE_TEST_ROOM_FLAG;
		_map[0x41] = OPCODE_NOT_HAVE_OBJECT;
		_map[0x45] = OPCODE_NOT_IN_ROOM;
		_map[0x48] = OPCODE_CURRENT_OBJECT_IS_NOWHERE;
		_map[0x49] = OPCODE_OBJECT_NOT_PRESENT;
		_map[0x43] = OPCODE_OBJECT_NOT_IN_ROOM;
		_map[0x50] = OPCODE_TEST_FALSE;
		_map[0x59] = OPCODE_TEST_NOT_FLAG;
		_map[0x60] = OPCODE_NOT_HAVE_CURRENT_OBJECT;
		_map[0x61] = OPCODE_OBJECT_IS_NOWHERE;
		_map[0x64] = OPCODE_CURRENT_OBJECT_NOT_PRESENT;
		_map[0x68] = OPCODE_CURRENT_OBJECT_NOT_TAKEABLE;
		_map[0x71] = OPCODE_TEST_NOT_ROOM_FLAG;
		_map[0x80] = OPCODE_INVENTORY;
		_map[0x81] = OPCODE_TAKE_OBJECT;
		_map[0x82] = OPCODE_MOVE_OBJECT_TO_ROOM;
		_map[0x84] = OPCODE_SAVE_ACTION;
		_map[0x85] = OPCODE_MOVE_TO_ROOM;
		_map[0x86] = OPCODE_VAR_ADD;
		_map[0x87] = OPCODE_SET_ROOM_DESCRIPTION;
		_map[0x89] = OPCODE_MOVE_OBJECT_TO_CURRENT_ROOM;
		_map[0x8a] = OPCODE_VAR_SUB;
		_map[0x8b] = OPCODE_SET_OBJECT_DESCRIPTION;
		_map[0x8c] = OPCODE_MOVE;
		_map[0x8e] = OPCODE_PRINT;
		_map[0x95] = OPCODE_REMOVE_OBJECT;
		_map[0x99] = OPCODE_SET_FLAG;
		_map[0x92] = OPCODE_CALL_FUNC;
		_map[0x98] = OPCODE_TURN_TICK;
		_map[0x9d] = OPCODE_CLEAR_FLAG;
		_map[0x9e] = OPCODE_INVENTORY_ROOM;
		_map[0xa0] = OPCODE_TAKE_CURRENT_OBJECT;
		_map[0xa1] = OPCODE_SPECIAL;
		_map[0xa4] = OPCODE_DROP_CURRENT_OBJECT;
		_map[0xa2] = OPCODE_SET_ROOM_GRAPHIC;
		_map[0xb0] = OPCODE_REMOVE_CURRENT_OBJECT;
		_map[0xb1] = OPCODE_DO_VERB;
		_map[0xb9] = OPCODE_SET_STRING_REPLACEMENT;
		_map[0xbd] = OPCODE_VAR_INC;
		_map[0xc1] = OPCODE_VAR_DEC;
		_map[0xc9] = OPCODE_MOVE_CURRENT_OBJECT_TO_ROOM;
	}
};

} // namespace Comprehend
	
#endif // COMPREHEND_OPCODES_H
